### ISSUE TITLE
Deletion Doesn't work 

### ISSUE THREAD

**Issue by Vivek2k20** [niteshkumartiwari/B-Plus-Tree#4]
In some cases,Deletion doesn't work for keys not present in the tree. 
The following code is problematic in "removeKey" function in  "remove.cpp"

![222](https://user-images.githubusercontent.com/60169148/125169995-60e20280-e1ca-11eb-9ffb-a62e2d42114c.JPG)

Since we are setting the flag to false,This whole code can be replaced to  : 

`
if (found==false) {
		cout << "Key Not Found in the Tree" << endl;
		return;
	}
`

Or was there some issue that the original code was supposed to solve? 
The new code is tested and Seems to work.

**Comment by Vivek2k20** [comment]
The program also crashes when trying to delete a key ,and there is only one node present(root) and it contains less than the (maxchildleafnodes+1)/2 . This can be avoided by changing the condition at line 86 of remove. cpp as follows :
if ((cursor->keys.size() >= (getMaxLeafNodeLimit()+1) / 2)||(cursor==root))

**Comment by niteshkumartiwari** [comment]
Pl create PR for the fix, if you want to contribute.

**Comment by niteshkumartiwari** [comment]
Updated : https://github.com/niteshkumartiwari/B-Plus-Tree/pull/10
