### ISSUE TITLE
B+TREE.CPP NOT WORKING

### ISSUE THREAD

**Issue by kushmishraa** [niteshkumartiwari/B-Plus-Tree#6]
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\lenovo\AppData\Local\Temp\ccNeksrm.o:Tree.cpp:(.text+0x2bd): undefined reference to `BPTree::insert(int, _iobuf*)'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\lenovo\AppData\Local\Temp\ccNeksrm.o:Tree.cpp:(.text+0x47a): undefined reference to `BPTree::search(int)'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\lenovo\AppData\Local\Temp\ccNeksrm.o:Tree.cpp:(.text+0x4f8): undefined reference to `BPTree::getRoot()'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\lenovo\AppData\Local\Temp\ccNeksrm.o:Tree.cpp:(.text+0x504): undefined reference to `BPTree::display(Node*)'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\lenovo\AppData\Local\Temp\ccNeksrm.o:Tree.cpp:(.text+0x50f): undefined reference to `BPTree::getRoot()'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\lenovo\AppData\Local\Temp\ccNeksrm.o:Tree.cpp:(.text+0x51b): undefined reference to `BPTree::seqDisplay(Node*)'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\lenovo\AppData\Local\Temp\ccNeksrm.o:Tree.cpp:(.text+0x562): undefined reference to `BPTree::getRoot()'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\lenovo\AppData\Local\Temp\ccNeksrm.o:Tree.cpp:(.text+0x56e): undefined reference to `BPTree::display(Node*)'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\lenovo\AppData\Local\Temp\ccNeksrm.o:Tree.cpp:(.text+0x5bd): undefined reference to `BPTree::removeKey(int)'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\lenovo\AppData\Local\Temp\ccNeksrm.o:Tree.cpp:(.text+0x5c6): undefined reference to `BPTree::getRoot()'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\lenovo\AppData\Local\Temp\ccNeksrm.o:Tree.cpp:(.text+0x5d2): undefined reference to `BPTree::display(Node*)'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\lenovo\AppData\Local\Temp\ccNeksrm.o:Tree.cpp:(.text+0x6a5): undefined reference to `BPTree::BPTree(int, int)'
collect2.exe: error: ld returned 1 exit status

THSES ARE THE ERRORS AND I CANT SOLVE'EM HOPE YOU WILL HELP

**Comment by niteshkumartiwari** [comment]
I cannot get much context from the logs above but it looks like the error is local to your machine. Please take a look at the readme for code setup. Run the application as a Console Application in Visual Studios Community edition.
